### ISSUE TITLE
[Feature Request] More `speed` options

### ISSUE THREAD

**Issue by zernyu** [ry-sun/bob-plugin-openai-tts#1]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/rockmagma02/bob-plugin-openai-tts/issues) and [Discussions](https://github.com/rockmagma02/bob-plugin-openai-tts/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/rockmagma02/bob-plugin-openai-tts/discussions/new).

### Motivation

I love this plugin! It works great. However, the default OpenAI speech is too slow, but I can only choose to 2x/3x/4x the speed, which is too fast for me and sounds unnatural.

### Solution

 Can we please add some more granular speed settings, such as 1.25, 1.5, 1.75? Thank you! 🙏🏼 

### Checklist

- [X] I have made every effort to write this issue in English, including all comments, the title, and the description.
- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by ry-sun** [comment]
sure, I'll change the speed options from a choices-list to text box **today**.

**Comment by ry-sun** [comment]
Hello @zernyu,

I have updated the plugin in PR #2. Please try the new version.

**Comment by zernyu** [comment]
@rockmagma02 Wow, that was quick. You are amazing! Just updated and the new input box method works great. Thank you 🙏🏼
